In [112]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder,FunctionTransformer

from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, StratifiedKFold, cross_val_predict, KFold ,  StratifiedKFold

from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score, log_loss, confusion_matrix
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [113]:
def cls_feature(X,max_cat = 10):
        #Agrupando features numéricas
    numeric_features  = [cls for cls in X.columns if X[cls].dtype == 'float64' or X[cls].dtype =='int64']
    # print('>>numeric_features:', numeric_features ,
          # len(numeric_features))


    #Agrupando features categoricas
    categorical_features = [cls for cls in X.columns if X[cls].dtypes == 'object' and X[cls].nunique()<=max_cat]
    # print('\n>>cat_features:', cat_features ,
          # len(cat_features))
    return numeric_features , categorical_features

In [114]:
def print_metrics(y_true, y_pred, y_pred_proba):
    
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_test, y_pred)
    logloss = log_loss(y_true, y_pred_proba)
    roc_auc = roc_auc_score(y_true, y_pred)

    print("Accuracy: {:.2f}".format(accuracy))
    print("Precision: {:.2f}".format(precision))
    print("Recall: {:.2f}".format(recall))
    print("F1-Score: {:.2f}".format(f1))
    print("Log Loss: {:.2f}".format(logloss))
    print("ROC AUC Score: {:.2f}".format(roc_auc))

In [188]:
def custom_features(df):
    df_out = df.copy()
    df_out['cat_empresa'] = df_out['ano_de_estabelecimento'].apply(lambda x: 'antiga' if x <= 1945 else
                                                                    'intermediaria' if 1945 < x < 1996 else
                                                                    'nova' if x >= 1996 else 'NaN')
    percentil_25 = np.percentile(df['salario_prevalecente'], 25)
    percentil_75 = np.percentile(df['salario_prevalecente'], 75)
    median = np.median(df['salario_prevalecente'])
    df_out['cat_salario'] = df_out['salario_prevalecente'].apply(lambda x: 'baixo' if x < percentil_25 else
                                                                'medio_baixo' if percentil_25 <= x < median else
                                                                'medio_alto' if median <= x < percentil_75 else
                                                                'alto' if x >= percentil_75 else 'NaN')
    
    # df_out['cat_salario'] = df_out['salario_prevalecente'].apply(lambda x: 'baixo' if x < np.percentile(df['salario_prevalecente'], 25) else
    #                                                                'medio_baixo' if np.percentile(df['salario_prevalecente'], 25) <= x < np.median(df['salario_prevalecente']) else
    #                                                                'medio_alto' if np.median(df['salario_prevalecente']) <= x < np.percentile(df['salario_prevalecente'], 75) else
    #                                                                'alto' if x >= np.percentile(df['salario_prevalecente'], 75) else 'NaN')
    df_out['cat_experiencia'] = 'Null'
    df_out.loc[(df_out['tem_experiencia_de_trabalho'] == 'S') & (df_out['requer_treinamento_de_trabalho'] == 'S'), 'cat_experiencia'] = '1'
    df_out.loc[(df_out['tem_experiencia_de_trabalho'] == 'S') & (df_out['requer_treinamento_de_trabalho'] == 'N'), 'cat_experiencia'] = '2'
    df_out.loc[(df_out['tem_experiencia_de_trabalho'] == 'N') & (df_out['requer_treinamento_de_trabalho'] == 'S'), 'cat_experiencia'] = '3'
    df_out.loc[(df_out['tem_experiencia_de_trabalho'] == 'N') & (df_out['requer_treinamento_de_trabalho'] == 'N'), 'cat_experiencia'] = '4'
    
    
    # Alterando a coluna Salario prevcalencente e unidade de salaio
    #df_out['unidade_de_salario'] = ' '
    
    df_out.loc[df_out['unidade_de_salario'] == 'Hora', 'salario_prevalecente'] *= 2080
    df_out.loc[df_out['unidade_de_salario'] == 'Semana', 'salario_prevalecente'] *= 52
    df_out.loc[df_out['unidade_de_salario'] == 'Mes', 'salario_prevalecente'] *= 12
    df_out.loc[df_out['unidade_de_salario'] == 'Ano', 'salario_prevalecente'] *= 1
    df_out['salario_anual'] = df_out['salario_prevalecente']
    
    
    # posição em tempo integral
    
    df_out['posicao_em_tempo_integral'] = df_out['posicao_em_tempo_integral'].map({'S': 1, 'N': 0})
    df_out['efeito_salario_emprego'] = df_out['salario_anual'] * df_out['posicao_em_tempo_integral']
    
    
    # qualificaçã do trabalho
    
    #df_out['qualificado_trabalho'] = df_out['educacao_do_empregado'] + df_out['tem_experiencia_de_trabalho']
    
    # relação salario/empregado
    df_out['salario_em_relacao_ao_num_de_empregados'] = df_out['salario_prevalecente'] / df_out['num_de_empregados']


        
    # mestrado e experiencia
    df_out['tem_mestrado_exp'] = '0'
    df_out.loc[(df_out['educacao_do_empregado']=='Mestrado') & (df_out['tem_experiencia_de_trabalho'] == 'S') , 'tem_mestrado_exp'] = '1'
    
    # america do norte 
    df_out['doutorado+AN'] = '0'
    df_out.loc[(df_out['continente']=='América do Norte') & (df_out['educacao_do_empregado'] == 'Doutorado') , 'doutorado+AN'] = '1'
    
    
    return df_out

## Data

In [189]:
data_train = pd.read_csv('data/train.csv'); data_train.head()

,id_do_caso,continente,educacao_do_empregado,tem_experiencia_de_trabalho,requer_treinamento_de_trabalho,num_de_empregados,ano_de_estabelecimento,regiao_de_emprego,salario_prevalecente,unidade_de_salario,posicao_em_tempo_integral,status_do_caso
0,EZYV10567,Europa,Ensino Médio,N,S,2087,1855,Sul,69711.24,Ano,S,Negado
1,EZYV5505,Ásia,Mestrado,S,N,5991,2003,Meio-Oeste,52931.38,Ano,S,Aprovado
2,EZYV5207,Ásia,Ensino Médio,N,N,1426,2000,Ilha,110830.21,Ano,S,Negado
3,EZYV7545,Ásia,Ensino Médio,N,N,3846,1992,Meio-Oeste,91884.68,Semana,S,Negado
4,EZYV16071,Ásia,Ensino Superior,S,N,3957,1949,Nordeste,138155.24,Ano,S,Aprovado

In [190]:
data_train.columns

Index(['id_do_caso', 'continente', 'educacao_do_empregado',
       'tem_experiencia_de_trabalho', 'requer_treinamento_de_trabalho',
       'num_de_empregados', 'ano_de_estabelecimento', 'regiao_de_emprego',
       'salario_prevalecente', 'unidade_de_salario',
       'posicao_em_tempo_integral', 'status_do_caso'],
      dtype='object')

In [191]:
df = data_train.copy()

In [192]:
df.drop(columns=['id_do_caso'],inplace = True)

In [193]:
df.sample(20)

,continente,educacao_do_empregado,tem_experiencia_de_trabalho,requer_treinamento_de_trabalho,num_de_empregados,ano_de_estabelecimento,regiao_de_emprego,salario_prevalecente,unidade_de_salario,posicao_em_tempo_integral,status_do_caso
15616,Ásia,Ensino Superior,N,N,2983,1998,Meio-Oeste,62141.0300,Ano,S,Aprovado
4579,América do Norte,Mestrado,S,N,92,1968,Nordeste,55920.4000,Ano,S,Negado
11373,Ásia,Mestrado,S,N,2898,1839,Meio-Oeste,59472.8000,Ano,S,Aprovado
6151,Europa,Ensino Superior,N,N,8338,2012,Nordeste,24167.7800,Ano,S,Aprovado
3166,Europa,Ensino Superior,N,N,2123,1993,Meio-Oeste,43006.7400,Ano,S,Negado
14509,Ásia,Ensino Superior,S,N,4540,1985,Oeste,51269.5800,Ano,S,Negado
2688,Europa,Mestrado,N,N,4848,1992,Oeste,19287.3900,Ano,S,Aprovado
6726,Europa,Mestrado,N,S,1029,1988,Nordeste,101522.1500,Ano,S,Aprovado
6403,Ásia,Mestrado,S,N,221,1881,Sul,82523.9100,Ano,N,Negado
9214,América do Norte,Ensino Superior,N,N,672,2013,Sul,12759.7000,Ano,S,Aprovado
16127,Ásia,Mestrado,N,N,1504,1985,Nordeste,737.4472,Hora,S,Negado
12533,Ásia,Ensino Médio,N,N,1762,2001,Nordeste,238.8305,Hora,S,Aprovado
4528,Ásia,Ensino Médio,N,S,3374,2003,Sul,30619.1900,Ano,S,Negado
3,Ásia,Ensino Médio,N,N,3846,1992,Meio-Oeste,91884.6800,Semana,S,Negado
12947,Ásia,Ensino Superior,N,S,866,1969,Sul,32624.3300,Ano,S,Aprovado
1214,África,Mestrado,N,N,768,1996,Oeste,98329.2300,Ano,S,Aprovado
3736,Ásia,Ensino Superior,N,N,3291,1998,Sul,198517.7400,Ano,S,Negado
7385,Europa,Mestrado,N,N,4198,2006,Oeste,54240.9400,Ano,S,Aprovado
7373,Europa,Doutorado,S,N,4330,2013,Oeste,23728.7300,Ano,S,Aprovado
17079,Ásia,Ensino Médio,S,N,1893,1995,Meio-Oeste,120298.2800,Ano,S,Negado

In [194]:
df['continente'].value_counts()

Ásia                11765
Europa               2654
América do Norte     2295
América do Sul        590
África                393
Oceania               139
Name: continente, dtype: int64

## Start

In [195]:
df['status_do_caso'].value_counts()

Aprovado    11937
Negado       5899
Name: status_do_caso, dtype: int64

In [196]:
df['status_do_caso'] = df['status_do_caso'].apply(lambda x: 1 if x == 'Aprovado' else 0)

In [197]:
df['status_do_caso'].value_counts()

1    11937
0     5899
Name: status_do_caso, dtype: int64

In [198]:
df.dtypes

continente                         object
educacao_do_empregado              object
tem_experiencia_de_trabalho        object
requer_treinamento_de_trabalho     object
num_de_empregados                   int64
ano_de_estabelecimento              int64
regiao_de_emprego                  object
salario_prevalecente              float64
unidade_de_salario                 object
posicao_em_tempo_integral          object
status_do_caso                      int64
dtype: object

In [199]:
X = df.drop(columns=['status_do_caso'])
y = df['status_do_caso']

In [200]:
df['ano_de_estabelecimento'] = np.log1p(df['ano_de_estabelecimento'])

## Prepro

In [201]:
custom_features(df)

,continente,educacao_do_empregado,tem_experiencia_de_trabalho,requer_treinamento_de_trabalho,num_de_empregados,ano_de_estabelecimento,regiao_de_emprego,salario_prevalecente,unidade_de_salario,posicao_em_tempo_integral,status_do_caso,cat_empresa,cat_salario,cat_experiencia,salario_anual,efeito_salario_emprego,salario_em_relacao_ao_num_de_empregados,tem_mestrado_exp,doutorado+AN
0,Europa,Ensino Médio,N,S,2087,7.526179,Sul,69711.24,Ano,1,0,antiga,medio_baixo,3,69711.24,69711.24,33.402607,0,0
1,Ásia,Mestrado,S,N,5991,7.602900,Meio-Oeste,52931.38,Ano,1,1,antiga,medio_baixo,2,52931.38,52931.38,8.835149,1,0
2,Ásia,Ensino Médio,N,N,1426,7.601402,Ilha,110830.21,Ano,1,0,antiga,alto,4,110830.21,110830.21,77.721045,0,0
3,Ásia,Ensino Médio,N,N,3846,7.597396,Meio-Oeste,4778003.36,Semana,1,0,antiga,medio_alto,4,4778003.36,4778003.36,1242.330567,0,0
4,Ásia,Ensino Superior,S,N,3957,7.575585,Nordeste,138155.24,Ano,1,1,antiga,alto,2,138155.24,138155.24,34.914137,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17831,Ásia,Mestrado,S,N,95347,7.598900,Oeste,69692.24,Ano,1,1,antiga,medio_baixo,2,69692.24,69692.24,0.730933,1,0
17832,Europa,Ensino Médio,N,N,1483,7.542744,Sul,136237.62,Ano,1,0,antiga,alto,4,136237.62,136237.62,91.866231,0,0
17833,América do Norte,Mestrado,N,N,1504,7.606387,Nordeste,118187.30,Ano,1,0,antiga,alto,4,118187.30,118187.30,78.581981,0,0
17834,América do Norte,Doutorado,S,N,251967,7.606387,Meio-Oeste,93133.40,Ano,1,1,antiga,medio_alto,2,93133.40,93133.40,0.369625,0,1
17835,Ásia,Ensino Superior,S,N,4116,7.605392,Oeste,71500.57,Ano,1,1,antiga,medio_alto,2,71500.57,71500.57,17.371373,0,0

In [202]:
custom_features(df).shape

(17836, 19)

In [203]:
feature_engineering_transformer = FunctionTransformer(custom_features)

In [204]:
numeric_features , categorical_features = cls_feature(custom_features(X))

In [205]:
numeric_features

['num_de_empregados',
 'ano_de_estabelecimento',
 'salario_prevalecente',
 'posicao_em_tempo_integral',
 'salario_anual',
 'efeito_salario_emprego',
 'salario_em_relacao_ao_num_de_empregados']

In [206]:
categorical_features

['continente',
 'educacao_do_empregado',
 'tem_experiencia_de_trabalho',
 'requer_treinamento_de_trabalho',
 'regiao_de_emprego',
 'unidade_de_salario',
 'cat_empresa',
 'cat_salario',
 'cat_experiencia',
 'tem_mestrado_exp',
 'doutorado+AN']

In [207]:
categorical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value='missing')),
    ('enconder',OneHotEncoder(handle_unknown='ignore',sparse=False)),
    
])
numerical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])


preprocessor = ColumnTransformer([
        ("num", numerical_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
]
)

pipeline_fe = Pipeline(steps=[
    ('fe', feature_engineering_transformer),
    ('preprocessor', preprocessor)])

In [208]:
X_preprocessed_fe = pipeline_fe.fit_transform(X)

In [209]:
X_preprocessed_fe.shape

(17836, 45)

In [210]:
y.shape

(17836,)

In [211]:
X_train, X_test, y_train, y_test = train_test_split(X_preprocessed_fe, y, test_size=0.2, random_state=42)

In [71]:
# # Dividir os dados em conjuntos de treinamento e teste
# X_train, X_test, y_train, y_test = train_test_split(X_preprocessed_fe, y, test_size=0.2, random_state=42)

# # Definir os modelos
# models = {
#     'RandomForest': RandomForestClassifier(class_weight='balanced', random_state=42),
#     'XGBoost': XGBClassifier(random_state=42,class_weight='balanced'),
#     'LGBM': LGBMClassifier(random_state=42,class_weight = 'balanced')
# }

# # Definir as grades de hiperparâmetros para cada modelo
# param_grids = {
#     'RandomForest': {
#         'n_estimators': [100, 200, 500,1000],
#         'max_depth': [None, 10, 30],
#         'min_samples_split': [2, 5, 10],
#         'criterion': ['gini', 'entropy']
#     },
#     'XGBoost': {
#         'n_estimators': [100, 200, 500,1000],
#         'learning_rate': [0.001, 0.1, 0.3],
#         'max_depth': [3, 6, 10]
        
#     },
#     'LGBM':{
#         'learning_rate': [0.001, 0.1, 0.3],
#         'num_leaves':[2,16,64,128],
#         'min_child_samples':[1,40,70,100]
        
        
#     }
# }

# # Validação cruzada com 3 folds
# cv = KFold(n_splits=3, shuffle=True, random_state=42)

# # Treinar e ajustar os modelos
# grids = {} # armazenará os modelos
# for model_name, model in models.items():
#     grids[model_name] = GridSearchCV(estimator=model, param_grid=param_grids[model_name], cv=cv, scoring='f1', n_jobs=-1, verbose=1)
#     grids[model_name].fit(X_train, y_train)
#     best_params = grids[model_name].best_params_
#     best_score = grids[model_name].best_score_
    
#     # Prever os rótulos do conjunto de teste
#     y_pred = grids[model_name].predict(X_test)
    
#     # Calcular o F1 score para o conjunto de teste
#     f1 = f1_score(y_test, y_pred)
    
#     # Imprimir os resultados
#     print(f'Best parameters for {model_name}: {best_params}')
#     print(f'Best F1 score for {model_name}: {best_score}')
#     print(f'F1 score on test set for {model_name}: {f1}\n')

In [ ]:

# # Definir os modelos
# models = {
#     'RandomForest': RandomForestClassifier(class_weight='balanced', random_state=42),
#     'XGBoost': XGBClassifier(random_state=42)
# }

# # Definir as grades de hiperparâmetros para cada modelo
# param_distributions = {
#     'RandomForest': {
#         'n_estimators': [100, 200, 500, 1000],
#         'max_depth': [None, 10, 30],
#         'min_samples_split': [2, 5, 10],
#         'criterion': ['gini', 'entropy']
#     },
#     'XGBoost': {
#         'n_estimators': [100, 200, 500, 1000],
#         'learning_rate': [1e-3, 1e-1,1],
#         'max_depth': [1,3, 6, 10],
#         'subsample':[0.5,1],
#         'min_child_weight' :[1,10],
#         'colsample_bytree':[0.5,1]
      
#     }
# }

# # Validação cruzada com 3 folds
# cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# # Treinar e ajustar os modelos
# searches = {}
# for model_name, model in models.items():
#     searches[model_name] = RandomizedSearchCV(estimator=model, param_distributions=param_distributions[model_name], scoring='f1', n_iter=10, cv=cv, random_state=42, n_jobs=-1, verbose=2)
#     searches[model_name].fit(X_preprocessed_fe, y)
#     best_params = searches[model_name].best_params_
#     best_score = searches[model_name].best_score_
  
  
#     y_pred = searches[model_name].predict(X_test)

#     f1 = f1_score(y_test, y_pred)

#     # Imprimir os resultados
#     print(f'Best parameters for {model_name}: {best_params}')
#     print(f'Best F1 score for {model_name}: {best_score}\n')
#     print(f'F1 score on test set for {model_name}: {f1}\n')

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for RandomForest: {'n_estimators': 100, 'min_samples_split': 2, 'max_depth': None, 'criterion': 'gini'}
Best F1 score for RandomForest: 0.8068184348020293

F1 score on test set for RandomForest: 1.0

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for XGBoost: {'subsample': 0.5, 'n_estimators': 200, 'min_child_weight': 10, 'max_depth': 10, 'learning_rate': 0.001, 'colsample_bytree': 1}
Best F1 score for XGBoost: 0.8238136111962336

F1 score on test set for XGBoost: 0.8344111307074269

In [29]:
best_params

{'subsample': 0.5,
 'n_estimators': 200,
 'min_child_weight': 10,
 'max_depth': 10,
 'learning_rate': 0.001,
 'colsample_bytree': 1}

- {'subsample': 0.5,
-  'n_estimators': 200,
-  'min_child_weight': 10,
-  'max_depth': 10,
-  'learning_rate': 0.001,
-  'colsample_bytree': 1}

In [212]:
# Definir os modelos
models = {
    'RandomForest': RandomForestClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42),
    'GradientBoosting': GradientBoostingClassifier(random_state=42),
    'LGBM': LGBMClassifier(random_state=42)
}

# Definir as grades de hiperparâmetros para cada modelo
param_distributions = {
    'RandomForest': {
        'n_estimators': [100, 200, 500, 1000],
        'max_depth': [None, 10, 30],
        'min_samples_split': [2, 5, 10],
        'criterion': ['gini', 'entropy']
    },
    'XGBoost': {
        'n_estimators': [100, 200, 500, 1000],
        'learning_rate': [0.001, 0.1, 0.3],
        'max_depth': [3, 6, 10],
        'subsample': [0.5, 1],
        'min_child_weight': [1, 10],
        'colsample_bytree': [0.5, 1]
    },
    'GradientBoosting': {
        'n_estimators': [100, 200, 500, 1000],
        'learning_rate': [0.001, 0.1, 0.3],
        'max_depth': [3, 6, 10],
        'subsample': [0.5, 1],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4]
    },
    'LGBM': {
        'learning_rate': [0.001, 0.1, 0.3],
        'num_leaves': [2, 16, 64, 128],
        'min_child_samples': [1, 40, 70, 100]
    }
}

# Validação cruzada com 3 folds
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# Treinar e ajustar os modelos
searches = {}
for model_name, model in models.items():
    searches[model_name] = RandomizedSearchCV(estimator=model, param_distributions=param_distributions[model_name], scoring='f1', n_iter=10, cv=cv, random_state=42, n_jobs=-1, verbose=2)
    searches[model_name].fit(X_preprocessed_fe, y)
    best_params = searches[model_name].best_params_
    best_score = searches[model_name].best_score_
    
    # Prever os rótulos do conjunto de teste
    y_pred = searches[model_name].predict(X_test)
    
    # Calcular o F1 score para o conjunto de teste
    f1 = f1_score(y_test, y_pred)
    
    # Imprimir os resultados
    print(f'Best parameters for {model_name}: {best_params}')
    print(f'Best F1 score for {model_name}: {best_score}')
    print(f'F1 score on test set for {model_name}: {f1}\n')

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for RandomForest: {'n_estimators': 500, 'min_samples_split': 5, 'max_depth': 10, 'criterion': 'entropy'}
Best F1 score for RandomForest: 0.8250356876038024
F1 score on test set for RandomForest: 0.8453928225024249

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for XGBoost: {'subsample': 1, 'n_estimators': 500, 'min_child_weight': 10, 'max_depth': 10, 'learning_rate': 0.001, 'colsample_bytree': 0.5}
Best F1 score for XGBoost: 0.824941137563978
F1 score on test set for XGBoost: 0.8414774913428241

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for GradientBoosting: {'subsample': 1, 'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 3, 'learning_rate': 0.1}
Best F1 score for GradientBoosting: 0.8167726559954497
F1 score on test set for GradientBoosting: 0.8536728697355535

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters for LGBM: {'num_leaves': 16, 'min_child_samples': 70, 'learning_rate': 0.1}
Best F1 score for LGBM: 0.8230216638280742
F1 score on test set for LGBM: 0.8383679874460572

[CV] END criterion=entropy, max_depth=30, min_samples_split=2, n_estimators=500; total time=   8.2s
[CV] END criterion=gini, max_depth=30, min_samples_split=10, n_estimators=500; total time=   6.1s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=500, subsample=1; total time=   5.7s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=200, subsample=0.5; total time=   5.3s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=100, subsample=1; total time=   0.8s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=1000, subsample=0.5; total time=  26.3s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=500, subsample=0.5; total time=   7.5s
[CV] END learning_rate=0.1, max_depth=10, min_samples_leaf=4, min_samples_split=10, n_estimators=500, subsample=1; total time=  42.2s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=5, n_estimators=1000, subsample=1; total time=  24.0s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=64; total time=   0.3s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END criterion=entropy, max_depth=30, min_samples_split=2, n_estimators=500; total time=   7.8s
[CV] END criterion=gini, max_depth=None, min_samples_split=10, n_estimators=500; total time=   6.2s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=500, subsample=1; total time=  12.4s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=1000, subsample=0.5; total time=  26.3s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=1; total time=   8.4s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=1, min_samples_split=2, n_estimators=100, subsample=0.5; total time=   2.6s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=1, min_samples_split=2, n_estimators=100, subsample=0.5; total time=   2.6s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=1, min_samples_split=2, n_estimators=100, subsample=0.5; total time=   2.6s
[CV] END learning_rate=0.3, max_depth=3, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=0.5; total time=   1.5s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=  10.0s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=   9.8s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=5, n_estimators=1000, subsample=1; total time=  28.2s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END learning_rate=0.001, min_child_samples=100, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=16; total time=   0.2s
[CV] END criterion=gini, max_depth=None, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=gini, max_depth=None, min_samples_split=2, n_estimators=100; total time=   1.3s
[CV] END criterion=gini, max_depth=30, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=gini, max_depth=30, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=gini, max_depth=None, min_samples_split=10, n_estimators=500; total time=   6.3s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.7s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=6, min_child_weight=1, n_estimators=100, subsample=0.5; total time=   2.8s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=6, min_child_weight=1, n_estimators=100, subsample=0.5; total time=   2.9s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=10, min_child_weight=1, n_estimators=500, subsample=1; total time=  23.6s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=6, min_child_weight=10, n_estimators=500, subsample=1; total time=   6.8s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=  16.8s
[CV] END learning_rate=0.3, max_depth=3, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=0.5; total time=   1.5s
[CV] END learning_rate=0.001, max_depth=6, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=   9.9s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=5, n_estimators=1000, subsample=1; total time=  29.4s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=4, min_samples_split=5, n_estimators=500, subsample=1; total time=  11.4s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=64; total time=   0.3s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.3, min_child_samples=40, num_leaves=16; total time=   0.1s
[CV] END learning_rate=0.001, min_child_samples=40, num_leaves=2; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=gini, max_depth=None, min_samples_split=2, n_estimators=100; total time=   1.3s
[CV] END criterion=gini, max_depth=None, min_samples_split=2, n_estimators=100; total time=   1.3s
[CV] END criterion=gini, max_depth=30, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=500; total time=   5.3s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   1.0s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.8s
[CV] END colsample_bytree=1, learning_rate=0.3, max_depth=6, min_child_weight=1, n_estimators=100, subsample=0.5; total time=   2.8s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=200, subsample=0.5; total time=   5.2s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=10, min_child_weight=1, n_estimators=500, subsample=1; total time=  23.6s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1; total time=   2.5s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1; total time=   2.5s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=  16.9s
[CV] END learning_rate=0.001, max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=500, subsample=1; total time=  42.5s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END learning_rate=0.3, min_child_samples=40, num_leaves=16; total time=   0.1s
[CV] END learning_rate=0.001, min_child_samples=40, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=16; total time=   0.1s
[CV] END criterion=entropy, max_depth=30, min_samples_split=2, n_estimators=500; total time=   7.9s
[CV] END criterion=gini, max_depth=30, min_samples_split=10, n_estimators=500; total time=   6.1s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=500, subsample=1; total time=  12.4s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=1000, subsample=0.5; total time=  26.2s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=500, subsample=0.5; total time=   7.5s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=1; total time=   8.2s
[CV] END learning_rate=0.3, max_depth=3, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=0.5; total time=   1.5s
[CV] END learning_rate=0.001, max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=500, subsample=1; total time=  41.3s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END learning_rate=0.3, min_child_samples=40, num_leaves=16; total time=   0.1s
[CV] END learning_rate=0.001, min_child_samples=40, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=16; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=500; total time=   5.1s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   1.0s
[CV] END criterion=gini, max_depth=10, min_samples_split=2, n_estimators=100; total time=   0.9s
[CV] END criterion=entropy, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.7s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=500, subsample=1; total time=   5.7s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=10, min_child_weight=1, n_estimators=500, subsample=1; total time=  23.6s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=6, min_child_weight=10, n_estimators=500, subsample=1; total time=   6.8s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=4, min_samples_split=5, n_estimators=200, subsample=1; total time=  17.2s
[CV] END learning_rate=0.001, max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=500, subsample=1; total time=  43.2s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END learning_rate=0.001, min_child_samples=100, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=1, num_leaves=128; total time=   0.4s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.1s
[CV] END criterion=entropy, max_depth=10, min_samples_split=2, n_estimators=500; total time=   5.0s
[CV] END criterion=gini, max_depth=30, min_samples_split=10, n_estimators=500; total time=   6.0s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=500, subsample=1; total time=   5.7s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=200, subsample=0.5; total time=   5.3s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=100, subsample=1; total time=   0.8s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=3, min_child_weight=10, n_estimators=100, subsample=1; total time=   0.7s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=6, min_child_weight=10, n_estimators=500, subsample=0.5; total time=  15.3s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=6, min_child_weight=10, n_estimators=500, subsample=0.5; total time=  14.0s
[CV] END learning_rate=0.3, max_depth=10, min_samples_leaf=1, min_samples_split=10, n_estimators=100, subsample=1; total time=   8.3s
[CV] END learning_rate=0.1, max_depth=10, min_samples_leaf=4, min_samples_split=10, n_estimators=500, subsample=1; total time=  42.2s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=4, min_samples_split=5, n_estimators=500, subsample=1; total time=  13.6s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=128; total time=   0.5s
[CV] END learning_rate=0.1, min_child_samples=1, num_leaves=128; total time=   0.4s
[CV] END criterion=gini, max_depth=None, min_samples_split=5, n_estimators=100; total time=   1.2s
[CV] END criterion=gini, max_depth=10, min_samples_split=5, n_estimators=500; total time=   4.1s
[CV] END criterion=gini, max_depth=None, min_samples_split=10, n_estimators=500; total time=   6.3s
[CV] END colsample_bytree=0.5, learning_rate=0.001, max_depth=10, min_child_weight=10, n_estimators=500, subsample=1; total time=  12.5s
[CV] END colsample_bytree=1, learning_rate=0.001, max_depth=6, min_child_weight=10, n_estimators=500, subsample=0.5; total time=  15.4s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=6, min_child_weight=10, n_estimators=500, subsample=1; total time=   6.7s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=3, min_child_weight=1, n_estimators=200, subsample=1; total time=   2.4s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=500, subsample=0.5; total time=   7.6s
[CV] END learning_rate=0.1, max_depth=10, min_samples_leaf=4, min_samples_split=10, n_estimators=500, subsample=1; total time=  43.0s
[CV] END learning_rate=0.1, max_depth=3, min_samples_leaf=4, min_samples_split=5, n_estimators=500, subsample=1; total time=  13.6s
[CV] END learning_rate=0.3, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=64; total time=   0.3s
[CV] END learning_rate=0.1, min_child_samples=70, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.001, min_child_samples=100, num_leaves=2; total time=   0.1s
[CV] END learning_rate=0.1, min_child_samples=1, num_leaves=128; total time=   0.4s

## melhores modelos

### RandomForest
- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for RandomForest: {'n_estimators': 500, 'min_samples_split': 2, 'max_depth': 10, 'criterion': 'entropy'}
- Best F1 score for RandomForest: 0.8250298436905016
- F1 score on test set for RandomForest: 0.8497670807453416

### XGBoost

- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for XGBoost: {'subsample': 0.5, 'n_estimators': 1000, 'min_child_weight': 10, 'max_depth': 10, 'learning_rate': 0.001, 'colsample_bytree': 0.5}
- Best F1 score for XGBoost: 0.8233914509469814
- F1 score on test set for XGBoost: 0.8401229823212913

### GradientBoosting
- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for GradientBoosting: {'subsample': 1, 'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 3, 'learning_rate': 0.1}
- Best F1 score for GradientBoosting: 0.816277764149207
- F1 score on test set for GradientBoosting: 0.8546168958742633

### LGBM
- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for LGBM: {'num_leaves': 16, 'min_child_samples': 70, 'learning_rate': 0.1}
- Best F1 score for LGBM: 0.8218486603875013
- F1 score on test set for LGBM: 0.8390397481306572

### Random Forest
- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for RandomForest: {'n_estimators': 500, 'min_samples_split': 2, 'max_depth': 30, 'criterion': 'entropy'}
- Best F1 score for RandomForest: 0.8075161410111065
- F1 score on test set for RandomForest: 0.8235983590545028

### XGBoost
- Fitting 3 folds for each of 10 candidates, totalling 30 fits
- Best parameters for XGBoost: {'subsample': 1, 'n_estimators': 100, 'min_child_weight': 1, 'max_depth': 6, 'learning_rate': 0.001, 'colsample_bytree': 0.5}
- Best F1 score for XGBoost: 0.8250651531105628
- F1 score on test set for XGBoost: 0.8235983590545028

### Random Forest
- Fitting 3 folds for each of 54 candidates, totalling 162 fits
- Best parameters for RandomForest: {'criterion': 'gini', 'max_depth': 30, 'min_samples_split': 2, 'n_estimators': 500}
- Best F1 score for RandomForest: 0.803983160450065
- F1 score on test set for RandomForest: 0.8011928429423459

### Xgboost
- Fitting 3 folds for each of 27 candidates, totalling 81 fits
- Best parameters for XGBoost: {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 500}
- Best F1 score for XGBoost: 0.8237540956961373
- F1 score on test set for XGBoost: 0.8294094944037051

## Modelos emsemble

In [249]:
xgboost_params = {'subsample': 0.5, 'n_estimators': 1000, 'min_child_weight': 10, 'max_depth': 10, 'learning_rate': 0.001, 'colsample_bytree': 0.5}
gradientboostin_params = {'subsample': 1, 'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 3, 'learning_rate': 0.1}
lgbm_params = {'num_leaves': 16, 'min_child_samples': 70, 'learning_rate': 0.1}
rf_params = {'n_estimators': 1000, 'min_samples_split': 2, 'max_depth': 10, 'criterion': 'entropy'}

In [254]:
# Instanciar os modelos
xgb_model = XGBClassifier(**xgboost_params,random_state = 42)
gb_model = GradientBoostingClassifier(**gradientboostin_params,random_state = 42)
lgbm_model = LGBMClassifier(class_weight='balanced',**lgbm_params,random_state = 42)
#rf_model = RandomForestClassifier(class_weight='balanced',random_state=42, **rf_params)

# Criar o ensemble
ensemble = VotingClassifier(estimators=[('xgb', xgb_model), ('gb', gb_model), ('lgbm', lgbm_model)], voting='hard',weights=[1.1,3,1])

# Treinar o ensemble
ensemble.fit(X_preprocessed_fe, y)

# Fazer previsões em novos dados
y_pred = ensemble.predict(X_test)

# Calcular a métrica desejada
f1 = f1_score(y_test, y_pred)
print(f'F1 score: {f1}')

F1 score: 0.8536728697355535

F1 score:0.8536728697355535

## Modelo

In [213]:
best_model = searches['GradientBoosting'].best_estimator_
y_pred = best_model.predict(X_test)
y_pred_proba = best_model.predict_proba(X_test)
print_metrics(y_test,y_pred,y_pred_proba)

Accuracy: 0.79
Precision: 0.81
Recall: 0.90
F1-Score: 0.85
Log Loss: 0.45
ROC AUC Score: 0.73

In [214]:
best_params = {'subsample': 1, 'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_depth': 3, 'learning_rate': 0.1}
model = GradientBoostingClassifier(**best_params)
# Treinar o modelo com todos os dados disponíveis
model.fit(X_preprocessed_fe, y)

GradientBoostingClassifier(min_samples_leaf=4, min_samples_split=5,
                           n_estimators=500, subsample=1)

In [215]:
f1 = f1_score(y_test, y_pred);f1

0.8536728697355535

In [226]:
p = np.zeros((X_test.shape[0], 5))
for seed in range(5):
    mdl = GradientBoostingClassifier(**best_params)

    mdl.fit(X_train, y_train)
    p[:, seed] = mdl.predict_proba(X_test)[:, 1]

In [229]:
p

array([[0.73609951, 0.73609951, 0.73609951, 0.73609951, 0.73609951],
       [0.6638021 , 0.6638021 , 0.6638021 , 0.6638021 , 0.6638021 ],
       [0.95163564, 0.95163564, 0.95163564, 0.95163564, 0.95163564],
       ...,
       [0.93582778, 0.93582778, 0.93582778, 0.93582778, 0.93582778],
       [0.49048237, 0.49048237, 0.49048237, 0.49048237, 0.49048237],
       [0.82511935, 0.82511935, 0.82511935, 0.82511935, 0.82511935]])

## Submitions

In [255]:
df_test = pd.read_csv('data/test.csv')
df_test.head()

,id_do_caso,continente,educacao_do_empregado,tem_experiencia_de_trabalho,requer_treinamento_de_trabalho,num_de_empregados,ano_de_estabelecimento,regiao_de_emprego,salario_prevalecente,unidade_de_salario,posicao_em_tempo_integral
0,EZYV22339,Ásia,Ensino Superior,S,N,2414,1973,Nordeste,103320.80,Ano,N
1,EZYV9333,Ásia,Mestrado,N,S,2928,1937,Oeste,49786.35,Ano,S
2,EZYV9740,Ásia,Ensino Superior,S,N,1836,1999,Oeste,60855.83,Ano,S
3,EZYV3328,Ásia,Ensino Superior,S,N,122,2004,Sul,82379.06,Semana,S
4,EZYV12321,América do Sul,Ensino Superior,S,S,1720,2003,Nordeste,6719.81,Ano,S

In [256]:
df_test_processed = pipeline_fe.transform(df_test)

In [257]:
df_test['status_do_caso'] = ensemble.predict(df_test_processed)

In [ ]:
# df_test['status_do_caso'] = model.predict(df_test_processed)

In [84]:
# df_test['status_do_caso']  = searches['GradientBoosting'].predict(df_test_processed)

In [77]:
# df_test['status_do_caso'] = best_model.predict(df_test_processed)

In [78]:
#df_test['status_do_caso'] = grids['XGBoost'].predict(df_test_processed)

In [258]:
submit_resp = df_test[['id_do_caso', 'status_do_caso']]

In [259]:
submit_resp

     id_do_caso  status_do_caso
0     EZYV22339               1
1      EZYV9333               1
2      EZYV9740               1
3      EZYV3328               1
4     EZYV12321               1
...         ...             ...
7639  EZYV19907               0
7640    EZYV576               0
7641   EZYV1804               1
7642  EZYV13543               1
7643  EZYV17903               1

[7644 rows x 2 columns]

In [260]:
submit_resp.to_csv('data/subs/submission_7_jun6_12;07.csv', index=False)